### ISSUE TITLE
error loading ISIS3 cube (post spiceinit) using Selene/Kaguya driver

### ISSUE THREAD

**Issue by thareUSGS** [USGS-Astrogeology/ale#375]
I'm not sure this is suppose to work but I am getting a "No Such Driver for Label". For Kaguya do I need to load PDS images only (as shown in the current notebook examples under knoten)?

version: Ale v0.8.0

```
>>> import ale
/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/__init__.py:22: UserWarning: ALESPICEROOT environment variable not set, Spice Drivers will not function correctly
  warnings.warn('ALESPICEROOT environment variable not set, Spice Drivers will not function correctly')
>>> from ale.drivers.selene_drivers import KaguyaTcPds3NaifSpiceDriver
>>> from ale.formatters.usgscsm_formatter import to_usgscsm
>>> from ale import util
>>> fileName =  "/work/users/jlaura/kaguyaTC_pair/TC2S2B0_01_03517N242E0048.cub"

>>> kernels = util.generate_kernels_from_cube(fileName, expand=True)
>>> usgscsm_str = ale.loads(fileName, props={'kernels': kernels}, formatter='usgscsm', verbose=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 79, in loads
    res = load(label, props, formatter, verbose=verbose)
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 76, in load
    raise Exception('No Such Driver for Label')
Exception: No Such Driver for Label

```

**Comment by jessemapel** [comment]
Can you set verbose=True in your load call and post the output?

**Comment by thareUSGS** [comment]
```

>>> usgscsm_str = ale.loads(fileName, props={'kernels': kernels}, formatter='usgscsm', verbose=True)
Trying <class 'ale.drivers.isis_ideal_drivers.IdealLsIsisLabelIsisSpiceDriver'>
Failed: 'SampleDetectors'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 71, in load
    return formatter(driver)
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/formatters/usgscsm_formatter.py", line 61, in to_usgscsm
    'sample' : driver.detector_center_sample
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/isis_ideal_drivers.py", line 185, in detector_center_sample
    return self.label['IsisCube']['Instrument']['SampleDetectors'] / 2.0
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'SampleDetectors'
Trying <class 'ale.drivers.mro_drivers.MroCtxIsisLabelIsisSpiceDriver'>
Failed: 'TC2'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/mro_drivers.py", line 34, in instrument_id
    return id_lookup[super().instrument_id]
KeyError: 'TC2'
Trying <class 'ale.drivers.co_drivers.CassiniIssPds3LabelNaifSpiceDriver'>
Failed: 'INSTRUMENT_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/co_drivers.py", line 96, in instrument_id
    return self.id_lookup[super().instrument_id]
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/base/label_pds3.py", line 29, in instrument_id
    return self.label['INSTRUMENT_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'INSTRUMENT_ID'
Trying <class 'ale.drivers.dawn_drivers.DawnFcPds3NaifSpiceDriver'>
Failed: 'INSTRUMENT_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/dawn_drivers.py", line 32, in instrument_id
    instrument_id = super().instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/base/label_pds3.py", line 29, in instrument_id
    return self.label['INSTRUMENT_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'INSTRUMENT_ID'
Trying <class 'ale.drivers.lro_drivers.LroLrocPds3LabelNaifSpiceDriver'>
Failed: 'INSTRUMENT_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/lro_drivers.py", line 35, in instrument_id
    instrument = super().instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/base/label_pds3.py", line 29, in instrument_id
    return self.label['INSTRUMENT_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'INSTRUMENT_ID'
Trying <class 'ale.drivers.mes_drivers.MessengerMdisIsisLabelNaifSpiceDriver'>
Failed: 'TC2'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/mes_drivers.py", line 243, in instrument_id
    return ID_LOOKUP[super().instrument_id]
KeyError: 'TC2'
Trying <class 'ale.drivers.mes_drivers.MessengerMdisPds3NaifSpiceDriver'>
Failed: 'INSTRUMENT_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/mes_drivers.py", line 75, in instrument_id
    return ID_LOOKUP[super().instrument_id]
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/base/label_pds3.py", line 29, in instrument_id
    return self.label['INSTRUMENT_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'INSTRUMENT_ID'
Trying <class 'ale.drivers.mex_drivers.MexHrscPds3NaifSpiceDriver'>
Failed: 'DETECTOR_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/mex_drivers.py", line 167, in instrument_id
    return self.label['DETECTOR_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'DETECTOR_ID'
Trying <class 'ale.drivers.mro_drivers.MroCtxIsisLabelNaifSpiceDriver'>
Failed: 'TC2'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/mro_drivers.py", line 88, in instrument_id
    return id_lookup[super().instrument_id]
KeyError: 'TC2'
Trying <class 'ale.drivers.mro_drivers.MroCtxPds3LabelNaifSpiceDriver'>
Failed: 'INSTRUMENT_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/mro_drivers.py", line 199, in instrument_id
    return id_lookup[super().instrument_id]
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/base/label_pds3.py", line 29, in instrument_id
    return self.label['INSTRUMENT_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'INSTRUMENT_ID'
Trying <class 'ale.drivers.selene_drivers.KaguyaTcPds3NaifSpiceDriver'>
Failed: 'INSTRUMENT_ID'

Traceback (most recent call last):
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 68, in load
    res.instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/selene_drivers.py", line 75, in instrument_id
    instrument = super().instrument_id
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/base/label_pds3.py", line 29, in instrument_id
    return self.label['INSTRUMENT_ID']
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/pvl/_collections.py", line 123, in __getitem__
    return dict_getitem(self, key)[0]
KeyError: 'INSTRUMENT_ID'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 79, in loads
    res = load(label, props, formatter, verbose=verbose)
  File "/home/thare/.conda/envs/ale/lib/python3.7/site-packages/ale/drivers/__init__.py", line 76, in load
    raise Exception('No Such Driver for Label')
Exception: No Such Driver for Label

```

**Comment by jessemapel** [comment]
So it turns out we don't have an ISIS Cube driver for Kaguya images. Try passing the PDS3 label to loads instead of the cube.

**Comment by thareUSGS** [comment]
will do - that is what I figured.

**Comment by jlaura** [comment]
Closing in favor of #495. This issue pseudo-resolves when one sets the ALESPICEROOT environment variable (though #494 should be addressed to make this more evident).
